services:
  influxdb:
    image: influxdb
    build:
      context: ./influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    env_file:
      - ./influxdb/env/influxdb.env
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/etc:/etc/influxdb2
    networks:
      - grafana_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 8080:3000
    user: "${UID}:${GID}"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - grafana_network
    depends_on:
      - influxdb

networks:
  grafana_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_grafana
