FROM ubuntu:latest

RUN apt-get update && apt-get install -y build-essential

# chmod 666 /dev/cpu/*/msr

# cd /var/lib/rapl/papi6.0.0/src
#./configure --with-components="rapl"
# make

# cd /var/lib/rapl/rapl_plot
# make
# ./rapl_plot ${RAPL_OUTPUT_DIR} ${RAPL_SECONDS_INTERVAL}